import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "@/app/styles/globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const openSans = Open_Sans({
  variable: "--font-open_sans",
  weight: ["400", "500"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} antialiased`}
      >
        <main className="min-h-screen bg-gray-50">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
